
CREATE TABLE TEMPORADA(
    ID_TEMPORADA NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    NOMBRE VARCHAR2(100),
    FECHAINICIO DATE,
    FECHAFIN DATE,
    ESTADO CHAR,
    TOTAL_INVERTIDO NUMBER,
    AÑO NUMBER,
    NUMERO NUMBER
);

 CREATE TABLE TEMPORAL(
NOMBRE VARCHAR2(100),
APELLIDO VARCHAR2(100),
PASSWORD VARCHAR2 (100),
USERNAME VARCHAR2 (100),
TEMPORADA VARCHAR2 (100),
ANIO_TEMPORADA NUMBER,
NUMERO NUMBER,
TIER  VARCHAR2(100),
JORNADA VARCHAR2(100),
DEPORTE VARCHAR2(100),
FECHA VARCHAR2(20),
E_VISITANTE VARCHAR2(100),
E_LOCAL VARCHAR2(100),
P_LOCAL INT NOT NULL,
P_VISITANTE INT NOT NULL,
R_VISITANTE INT NOT NULL,
R_LOCAL INT NOT NULL


);

CREATE TABLE JORNADATEMPORADA(
    ID_JORNADA NUMBER GENERATED ALWAYS AS IDENTITY,
    ID_TEMPORADA NUMBER,
    NOMBRE_JORNADA VARCHAR2(100),
    ESTADO CHAR,
    FECHAINICIO DATE,
    FECHAFIN DATE,
    PRIMARY KEY(ID_TEMPORADA, NOMBRE_JORNADA)
);

CREATE TABLE EVENTO(
    ID_EVENTO NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    LOCAL_ VARCHAR(100),
    VISITANTE VARCHAR(100),
    DEPORTE NUMBER,
    IDJORNADA VARCHAR2(3),
    ID_TEMPORADA NUMBER,
    RESLOCAL NUMBER,
    RESVISITANTE NUMBER,
    FECHA DATE
);

CREATE TABLE JUGADOREQUIPO(
    IDJGEQ NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    NOMBRE VARCHAR2(100)
);

CREATE TABLE DEPORTE(
    IDDEPORTE NUMBER GENERATED ALWAYS AS IDENTITY,
    DEPORTE VARCHAR2(100),
    COLOR VARCHAR2(100)
);

CREATE TABLE TIER (
    ID_TIER       NUMBER GENERATED ALWAYS AS IDENTITY,
    NOMBRE_TIER   VARCHAR2(100),
    PRECIO_TIER  NUMBER,
    PRIMARY KEY(ID_TIER)
);


CREATE TABLE USUARIO (
    USERNAME  VARCHAR2(100) NOT NULL,
    PASS      VARCHAR2(100),
    NOMBRE    VARCHAR2(100),
    APELLIDO  VARCHAR2(100),
    ID_TIER   NUMBER,
    FECHANACIMIENTO DATE NULL,
    FECHA_REGISTRO DATE NULL,
    CORREO   VARCHAR2(100),
    FOTOPERFIL  VARCHAR(100),
    PRIMARY KEY(USERNAME)
);


CREATE TABLE MEMBRESIA( 
    USERNAME VARCHAR2(100) NOT NULL,
    IDTEMPORADA NUMBER NOT NULL,
    ID_TIER     NUMBER NOT NULL,
    PUNTEO_TOTAL NUMBER NULL,
    PRIMARY KEY(USERNAME, IDTEMPORADA, ID_TIER)
); 

CREATE TABLE PREDICCION(
    USERNAME  VARCHAR(100) NOT NULL,
    FECHA_EVENTO DATE NOT NULL,
    MARCADORLOCAL NUMBER NULL,
    MARCADORVISITANTE NUMBER NULL,
    PUNTEO  NUMBER DEFAULT 0,
    LOCAL_ VARCHAR2(100),
    VISITANTE VARCHAR2(100),
    DEPORTE NUMBER,
    JORNADA VARCHAR2(3),
    ID_TEMPORADA NUMBER
);







INSERT INTO USUARIO VALUES ('Welmann2903', 'Keilita123', 'Welmann Saul', 'Paniagua Illescas', 0, '20-05-2001', '20-05-2021', 'welmann2903@gmail.com', 'fotica');
commit;

CREATE OR REPLACE PROCEDURE LOGIN 
(
  USR IN USUARIO.USERNAME%TYPE,
  CONTRA IN USUARIO.PASS%TYPE,
  CONTEO OUT INTEGER,
  IS_ADMIN OUT INTEGER
) AS 
BEGIN
    SELECT COUNT(*)
    INTO CONTEO
    FROM USUARIO
    WHERE USERNAME=USR
    AND CONTRA=PASS;  

    IF (USR = 'admin' AND
        CONTRA = 'Admin1234')
        then IS_ADMIN:=1;
    ELSE IS_ADMIN:=0;
    END IF;
END LOGIN;

CREATE OR REPLACE PROCEDURE NUEVOUSUARIO
    (
        USR IN USUARIO.USERNAME%TYPE,
        PASS IN USUARIO.PASS%TYPE,
        NOMBRE IN USUARIO.NOMBRE%TYPE,
        APELLIDO IN USUARIO.APELLIDO%TYPE,
        FECHANACIMIENTO IN VARCHAR2,
        FECHAREGISTRO IN VARCHAR2,
        CORREO IN USUARIO.CORREO%TYPE,
        RESPUESTA OUT INTEGER
    ) AS 
BEGIN 
    INSERT INTO USUARIO 
        VALUES (
            USR,
            PASS,
            NOMBRE,
            APELLIDO,
            0,
            TO_DATE(FECHANACIMIENTO, 'dd/mm/yyyy'),
            SYSDATE,
            CORREO,
            'FOTICO'
        );
        
    RESPUESTA:= 0;
    EXCEPTION
        WHEN OTHERS 
            THEN
                RESPUESTA:=1;
END NUEVOUSUARIO;
    
select * from USUARIO;



/*
 LLENADO DE TABLAS 
*/

INSERT INTO JUGADOREQUIPO (NOMBRE) 
SELECT DISTINCT E_VISITANTE  FROM TEMPORAL, (
SELECT DISTINCT E_LOCAL FROM TEMPORAL
);

INSERT INTO DEPORTE (DEPORTE) 
SELECT DISTINCT DEPORTE FROM TEMPORAL;

INSERT INTO TEMPORADA(NOMBRE, AÑO, NUMERO) 
(SELECT DISTINCT TEMPORADA, ANIO_TEMPORADA, NUMEROTEMPORADA FROM TEMPORAL);

INSERT INTO JORNADATEMPORADA(NOMBRE_JORNADA,ID_TEMPORADA)
SELECT DISTINCT TEMPORAL.JORNADA , TEMPORADA.ID_TEMPORADA
FROM  TEMPORAL,TEMPORADA WHERE TEMPORAL.TEMPORADA=TEMPORADA.NOMBRE;

INSERT INTO USUARIO(USERNAME, NOMBRE, APELLIDO, PASS)
SELECT DISTINCT USERNAME, NOMBRE, APELLIDO, PASSWORD FROM TEMPORAL;

INSERT INTO MEMBRESIA(USERNAME, IDTEMPORADA, ID_TIER)
SELECT DISTINCT USERNAME, ID_TEMPORADA, ID_TIER FROM 
TEMPORAL LEFT JOIN TEMPORADA ON TEMPORAL.TEMPORADA = TEMPORADA.NOMBRE
LEFT JOIN TIER ON TEMPORAL.TIER = TIER.NOMBRE_TIER;

INSERT INTO EVENTO(LOCAL_, VISITANTE, DEPORTE, IDJORNADA, ID_TEMPORADA, RESLOCAL, RESVISITANTE)
SELECT DISTINCT E_LOCAL, E_VISITANTE, DEPORTE.IDDEPORTE, JORNADA, TEMPORADA.ID_TEMPORADA, R_LOCAL, R_VISITANTE FROM
TEMPORAL
LEFT JOIN TEMPORADA ON TEMPORAL.TEMPORADA = TEMPORADA.NOMBRE
LEFT JOIN DEPORTE ON TEMPORAL.DEPORTE = DEPORTE.DEPORTE;


INSERT INTO PREDICCION(USERNAME, LOCAL_, VISITANTE, MARCADORLOCAL, MARCADORVISITANTE, JORNADA, ID_TEMPORADA, FECHA_EVENTO,DEPORTE)
SELECT DISTINCT USERNAME, E_LOCAL, E_VISITANTE, P_LOCAL, P_VISITANTE, JORNADA, ID_TEMPORADA, TO_DATE(FECHA, 'dd/mm/yyyy HH24:MI'), IDDEPORTE
FROM TEMPORAL LEFT JOIN TEMPORADA ON TEMPORAL.TEMPORADA = TEMPORADA.NOMBRE
LEFT JOIN DEPORTE ON TEMPORAL.DEPORTE = DEPORTE.DEPORTE;

